version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: always
    ports:
      - 80:80

volumes:
  data:
    driver: local
