CREATE SCHEMA IF NOT EXISTS `ddingcon` DEFAULT CHARACTER SET utf8;

USE ddingcon;

DROP TABLE IF EXISTS `member`;
DROP TABLE IF EXISTS `artist`;
DROP TABLE IF EXISTS `concert`;
DROP TABLE IF EXISTS `alarm`;
DROP TABLE IF EXISTS `subscription`;

CREATE TABLE IF NOT EXISTS `member` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(200) NOT NULL,
    `nickname`	VARCHAR(30)	NOT NULL UNIQUE,
    `name` VARCHAR(100)	NOT NULL,
    `phone_number` VARCHAR(30) NULL,
    `provider` VARCHAR(20) NOT NULL DEFAULT 'kakao',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
DEFAULT CHARACTER SET = utf8mb4
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `artist` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `ko_name` VARCHAR(50) NOT NULL,
    `en_name` VARCHAR(50) NOT NULL,
    `genre`	VARCHAR(50)	NOT NULL,
    `image_url`	VARCHAR(200) NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
DEFAULT CHARACTER SET = utf8mb4
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `concert` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `artist_id` BIGINT NOT NULL,
    `name` VARCHAR(50) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`artist_id`) REFERENCES artist(`id`)
)
DEFAULT CHARACTER SET = utf8mb4
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `alarm` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `subscription_id` VARCHAR(50) NOT NULL,
    `is_priorty` BOOLEAN NOT NULL,
    `alert_time` VARCHAR(20) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
DEFAULT CHARACTER SET = utf8mb4
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `subscription` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `member_id`	BIGINT NOT NULL,
    `artist_id`	BIGINT NOT NULL,
    `is_priority` BOOLEAN NOT NULL,
    `is_activated`	BOOLEAN	NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`artist_id`) REFERENCES artist(`id`),
    FOREIGN KEY (`member_id`) REFERENCES member(`id`)
)
DEFAULT CHARACTER SET = utf8mb4
ENGINE = InnoDB;
